### PR TITLE
JBPM-7027 Stunner - docking event to the specific edge of activity 

### PR DESCRIPTION
**Pull request by tiagodolphine**
Fix tests and cherry pick c23e60ff95d880ca0f35c1d49a8050cc2b975dba 7a982c0ba27a1af223de9017bc5f378d8dd9fb1e

Related https://github.com/kiegroup/lienzo-core/pull/52

@romartin

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj I resolved the conflicts with master and pushed, the full downstream is ok to review.
Thanks.

**Comment by tiagodolphine** [comment]
@LuboTerifaj great catch, that was my fault when merging. I will fix that and fix the broken tests as well.
Thanks.

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
@LuboTerifaj I have updated the PR with the fixes, thanks!

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj great to find that, I added the tests and updated the PR.
Thanks.

**Comment by tiagodolphine** [comment]
@LuboTerifaj is it ok to merge?

**Comment by hasys** [comment]
Hi @manstis this PR is related to https://github.com/kiegroup/lienzo-core/pull/52 and ready to merge. Thank you!

**Pull request merged**
