### PR TITLE
added SCM tag for releasing

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@romartin I think we should add lienzo-core and lienzo-tests to out repository-list.txt, because the DSL created Jenkins jobs (lienzo-core and lienzo-tests) on master take the repository-list.txt into account. And it seems as they are not there the whole build of all reps are in upstream and so build before. The lienzo takes ages because of this.

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Pull request merged**
