### PR TITLE
JBPM-7532: Stunner - it is possible to corrupt diagram and lose all made changes

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @tiagobento @hasys would you mind review this PR?
Thanks!

p.s. depends on https://github.com/kiegroup/lienzo-core/pull/63

**Comment by wmedvede** [comment]
Hello @tiagodolphine , would you mind review this PR?
Thanks

**Comment by hasys** [comment]
Looks and works good, thank you @wmedvede!

P.S. Manually tested with https://github.com/kiegroup/kie-wb-common/pull/2150

**Comment by hasys** [comment]
@wmedvede,

just a question: did you found out why this method is always true? https://github.com/wmedvede/lienzo-core/pull/1#issue-218599536 

If not, I guess we should create a jira issue for it.

**Comment by wmedvede** [comment]
@romartin this has been around for two weeks now. Let's try to merge before we start getting merge errors.
Thanks.

**Pull request merged**
